project:
  type: website
  output-dir: ../docs/_site # Render the website to a nested directory

website:
  title: "academicCVTemplate"
  search:
    location: navbar
    type: overlay
  navbar:
    tools:
      - icon: github
        href:  https://github.com/orehren/academicCVTemplate
    left:
      - href: index.qmd
        text: Home
      - href: installation.qmd
        text: Installation
      - href: data_integration.qmd
        text: Data Integration
      - href: tutorial.qmd
        text: How to get started
      - href: shortcodes.qmd
        text: Shortcodes
      - href: styling.qmd
        text: Styling
      - href: structure.qmd
        text: Structure
      - href: yaml_reference.qmd
        text: YAML Reference
      - href: acknowledgements.qmd
        text: Acknowledgements

format:
  html:
    theme: cosmo
    toc: true
    keep-md: true # Keep the markdown files

execute:
  eval: false # Don't execute code chunks for the website
